name: CI/CD

on:
  push:
    branches:
      - main
      - CI

env:
  DOCKER_HUB_USERNAME: your_username
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        logout: false
            
    - name: Build and push Docker image
      env:
          DOCKER_IMAGE_NAME: uday1kiran/sample-app-nodejs
      run: |
          cd apps
          ## echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username $DOCKER_HUB_USERNAME --password-stdin
          docker build -t $DOCKER_IMAGE_NAME .
          docker push $DOCKER_IMAGE_NAME

    # - name: Deploy to Kubernetes
    #   uses: azure/k8s-set-context@v1
    #   with:
    #     method: kubeconfig
    #     kubeconfig: ${{ secrets.KUBECONFIG }}
        
    # - name: Apply Kubernetes manifest
    #   run: kubectl apply -f your-kubernetes-manifest.yaml
